### ISSUE TITLE
New app installation fails on authentication when hosted on heroku

### ISSUE THREAD

**Issue by neycodes** [Shopify/shopify_app#454]
I've encountered an authentication issue when installing a new app hosted on heroku. At first I thought it was just in my app, but when I couldn't find the problem I created a another test app to see if the same issue would occur, and it did.

I posted on the Shopify forums  a few days ago about this issue, but have not received any feedback there.

I have created a repo of my test app: [https://github.com/neycodes/shopify_test_app](https://github.com/neycodes/shopify_test_app)

In the readme of the repo I have added the steps I took leading up to the issue. Hopefully this helps to solve the problem.

Thanks!

**Comment by kevinhughes27** [comment]
Weird error - an actual ruby exception! We almost always get oauth token issues. 

I just released version 8.0.0. Can you test against that version? I think 7.4.0 might have had some things that clash with the latest Rails.

Let me know what happens and we'll get to the bottom of this 😄

**Comment by neycodes** [comment]
Hi Kevin,

I updated the gem to 8.0.0 and now get the error `NameError: uninitialized constant ShopifyApp::Shop`

Do we have to run the generators again?

**Comment by kevinhughes27** [comment]
that concern was removed - check the changelog if you are going to update your code. If your project doesn't have many changes after running the generator it might be easier to start over

**Comment by neycodes** [comment]
The project has a lot of changes after running the generator. What do you suggest?

**Comment by neycodes** [comment]
I removed the ShopifyApp::Shop concern. I don't see that stack trace in my heroku log anymore, but the install still fails. This is all I get in the logs now:

```
2017-08-14T16:52:03.055007+00:00 heroku[router]: at=info method=GET path="/" host=shopifyauthtest.herokuapp.com request_id=9d3c3057-4500-4e6a-b619-40b744bac213 fwd="96.232.156.16" dyno=web.1 connect=0ms service=15ms status=301 bytes=161 protocol=http
2017-08-14T16:52:03.123370+00:00 app[web.1]: [ed48c5f3-d6ba-4b70-aaba-80181b1d67ce] Started GET "/" for 96.232.156.16 at 2017-08-14 16:52:03 +0000
2017-08-14T16:52:03.133032+00:00 app[web.1]: [ed48c5f3-d6ba-4b70-aaba-80181b1d67ce] Processing by HomeController#index as HTML
2017-08-14T16:52:03.178005+00:00 app[web.1]: [ed48c5f3-d6ba-4b70-aaba-80181b1d67ce] Redirected to https://shopifyauthtest.herokuapp.com/login
2017-08-14T16:52:03.178582+00:00 app[web.1]: [ed48c5f3-d6ba-4b70-aaba-80181b1d67ce] Completed 302 Found in 45ms
2017-08-14T16:52:03.210411+00:00 app[web.1]: [7c725f08-deaa-48d6-9da5-5eb5725d347f] Started GET "/login" for 96.232.156.16 at 2017-08-14 16:52:03 +0000
2017-08-14T16:52:03.216799+00:00 app[web.1]: [7c725f08-deaa-48d6-9da5-5eb5725d347f] Processing by ShopifyApp::SessionsController#new as HTML
2017-08-14T16:52:03.230841+00:00 app[web.1]: [7c725f08-deaa-48d6-9da5-5eb5725d347f]   Rendering vendor/bundle/ruby/2.3.0/gems/shopify_app-8.0.0/app/views/shopify_app/sessions/new.html.erb
2017-08-14T16:52:03.232181+00:00 app[web.1]: [7c725f08-deaa-48d6-9da5-5eb5725d347f]   Rendered vendor/bundle/ruby/2.3.0/gems/shopify_app-8.0.0/app/views/shopify_app/sessions/new.html.erb (1.2ms)
2017-08-14T16:52:03.232576+00:00 app[web.1]: [7c725f08-deaa-48d6-9da5-5eb5725d347f] Completed 200 OK in 16ms (Views: 2.9ms)
2017-08-14T16:52:03.321571+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=shopifyauthtest.herokuapp.com request_id=030193a8-d42c-456a-bb34-355e7e58a6a4 fwd="96.232.156.16" dyno=web.1 connect=2ms service=2ms status=200 bytes=207 protocol=https
2017-08-14T16:52:32.863745+00:00 heroku[router]: at=info method=GET path="/login?shop=llp-dev.myshopify.com" host=shopifyauthtest.herokuapp.com request_id=d1121335-102e-4c95-af26-f3bd4454f19a fwd="96.232.156.16" dyno=web.1 connect=0ms service=7ms status=200 bytes=1817 protocol=https
2017-08-14T16:52:32.854971+00:00 app[web.1]: [d1121335-102e-4c95-af26-f3bd4454f19a] Started GET "/login?shop=llp-dev.myshopify.com" for 96.232.156.16 at 2017-08-14 16:52:32 +0000
2017-08-14T16:52:32.856274+00:00 app[web.1]: [d1121335-102e-4c95-af26-f3bd4454f19a] Processing by ShopifyApp::SessionsController#new as HTML
2017-08-14T16:52:32.856305+00:00 app[web.1]: [d1121335-102e-4c95-af26-f3bd4454f19a]   Parameters: {"shop"=>"llp-dev.myshopify.com"}
2017-08-14T16:52:32.859139+00:00 app[web.1]: [d1121335-102e-4c95-af26-f3bd4454f19a]   Rendering inline template
2017-08-14T16:52:32.859530+00:00 app[web.1]: [d1121335-102e-4c95-af26-f3bd4454f19a]   Rendered inline template (0.3ms)
2017-08-14T16:52:32.859694+00:00 app[web.1]: [d1121335-102e-4c95-af26-f3bd4454f19a] Completed 200 OK in 3ms (Views: 0.7ms)
2017-08-14T16:52:32.931389+00:00 app[web.1]: [ac456d4f-7d24-49df-9ced-d4698b024ee6] Started GET "/auth/shopify?shop=llp-dev.myshopify.com" for 96.232.156.16 at 2017-08-14 16:52:32 +0000
2017-08-14T16:52:32.931973+00:00 app[web.1]: I, [2017-08-14T16:52:32.931891 #7]  INFO -- omniauth: (shopify) Setup endpoint detected, running now.
2017-08-14T16:52:32.932240+00:00 app[web.1]: I, [2017-08-14T16:52:32.932184 #7]  INFO -- omniauth: (shopify) Request phase initiated.
```

**Comment by kevinhughes27** [comment]
It started the get to omniauth but then never came back. Does it work locally now? The app might be redirecting to the wrong place on production which is why it doesn't work.

**Comment by neycodes** [comment]
It installs locally, but now if I navigate away from the initial embedded home page I'm getting an console error `ERR_INSECURE_RESPONSE`.

**Comment by neycodes** [comment]
I uninstalled the app, restarted my local rails server and installed it again, and it installed locally this time without errors. Strange but the old reboot it if it's broken philosophy worked there.

I am tunneling into my local server using burrow.io.

I'll try it again now on heroku and report back.

**Comment by kevinhughes27** [comment]
Rails `initializers` are only loaded on boot so that could be what happened.

**Comment by neycodes** [comment]
Still failing on heroku. Here is the URL:
`https://shopifyauthtest.herokuapp.com/auth/shopify/callback?code=be4cb52cb292814293d7e8c65ec1abb7&hmac=9a8c83416a57edc752369470d2f43041f9de17e353307402d7d001fb9f2c906b&shop=llp-dev.myshopify.com&state=26c9f68f359d9f00ff9118eed37b21e55587d93ce5bed4f3&timestamp=1502736304`

And the log:
```
2017-08-14T18:45:04.235194+00:00 heroku[router]: at=info method=GET path="/auth/shopify/callback?code=be4cb52cb292814293d7e8c65ec1abb7&hmac=9a8c83416a57edc752369470d2f43041f9de17e353307402d7d001fb9f2c906b&shop=llp-dev.myshopify.com&state=26c9f68f359d9f00ff9118eed37b21e55587d93ce5bed4f3&timestamp=1502736304" host=shopifyauthtest.herokuapp.com request_id=fc17a4be-c098-4b88-b635-3f52a6e4bb23 fwd="96.232.156.16" dyno=web.1 connect=1ms service=5ms status=500 bytes=1891 protocol=https
2017-08-14T18:45:04.228699+00:00 app[web.1]: [fc17a4be-c098-4b88-b635-3f52a6e4bb23] Started GET "/auth/shopify/callback?code=be4cb52cb292814293d7e8c65ec1abb7&hmac=9a8c83416a57edc752369470d2f43041f9de17e353307402d7d001fb9f2c906b&shop=llp-dev.myshopify.com&state=26c9f68f359d9f00ff9118eed37b21e55587d93ce5bed4f3&timestamp=1502736304" for 96.232.156.16 at 2017-08-14 18:45:04 +0000
2017-08-14T18:45:04.229153+00:00 app[web.1]: I, [2017-08-14T18:45:04.229099 #11]  INFO -- omniauth: (shopify) Setup endpoint detected, running now.
2017-08-14T18:45:04.229325+00:00 app[web.1]: I, [2017-08-14T18:45:04.229283 #11]  INFO -- omniauth: (shopify) Callback phase initiated.
2017-08-14T18:45:04.230735+00:00 app[web.1]: [fc17a4be-c098-4b88-b635-3f52a6e4bb23]   
2017-08-14T18:45:04.230814+00:00 app[web.1]: [fc17a4be-c098-4b88-b635-3f52a6e4bb23] TypeError (no implicit conversion of nil into String):
2017-08-14T18:45:04.230866+00:00 app[web.1]: [fc17a4be-c098-4b88-b635-3f52a6e4bb23]   
2017-08-14T18:45:04.230969+00:00 app[web.1]: [fc17a4be-c098-4b88-b635-3f52a6e4bb23] vendor/bundle/ruby/2.3.0/gems/omniauth-shopify-oauth2-1.2.0/lib/omniauth/strategies/shopify.rb:85:in `hexdigest'
2017-08-14T18:45:04.230974+00:00 app[web.1]: [fc17a4be-c098-4b88-b635-3f52a6e4bb23] vendor/bundle/ruby/2.3.0/gems/omniauth-shopify-oauth2-1.2.0/lib/omniauth/strategies/shopify.rb:85:in `hmac_sign'
2017-08-14T18:45:04.230975+00:00 app[web.1]: [fc17a4be-c098-4b88-b635-3f52a6e4bb23] vendor/bundle/ruby/2.3.0/gems/omniauth-shopify-oauth2-1.2.0/lib/omniauth/strategies/shopify.rb:60:in `valid_signature?'
2017-08-14T18:45:04.230975+00:00 app[web.1]: [fc17a4be-c098-4b88-b635-3f52a6e4bb23] vendor/bundle/ruby/2.3.0/gems/omniauth-shopify-oauth2-1.2.0/lib/omniauth/strategies/shopify.rb:111:in `callback_phase'
2017-08-14T18:45:04.230976+00:00 app[web.1]: [fc17a4be-c098-4b88-b635-3f52a6e4bb23] vendor/bundle/ruby/2.3.0/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:230:in `callback_call'
2017-08-14T18:45:04.230977+00:00 app[web.1]: [fc17a4be-c098-4b88-b635-3f52a6e4bb23] vendor/bundle/ruby/2.3.0/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:187:in `call!'
2017-08-14T18:45:04.230978+00:00 app[web.1]: [fc17a4be-c098-4b88-b635-3f52a6e4bb23] vendor/bundle/ruby/2.3.0/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:167:in `call'
2017-08-14T18:45:04.230979+00:00 app[web.1]: [fc17a4be-c098-4b88-b635-3f52a6e4bb23] vendor/bundle/ruby/2.3.0/gems/omniauth-1.6.1/lib/omniauth/builder.rb:63:in `call'
2017-08-14T18:45:04.230979+00:00 app[web.1]: [fc17a4be-c098-4b88-b635-3f52a6e4bb23] vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/etag.rb:25:in `call'
2017-08-14T18:45:04.230980+00:00 app[web.1]: [fc17a4be-c098-4b88-b635-3f52a6e4bb23] vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/conditional_get.rb:25:in `call'
2017-08-14T18:45:04.230981+00:00 app[web.1]: [fc17a4be-c098-4b88-b635-3f52a6e4bb23] vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/head.rb:12:in `call'
2017-08-14T18:45:04.230981+00:00 app[web.1]: [fc17a4be-c098-4b88-b635-3f52a6e4bb23] vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:232:in `context'
2017-08-14T18:45:04.230982+00:00 app[web.1]: [fc17a4be-c098-4b88-b635-3f52a6e4bb23] vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:226:in `call'
2017-08-14T18:45:04.230983+00:00 app[web.1]: [fc17a4be-c098-4b88-b635-3f52a6e4bb23] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.3/lib/action_dispatch/middleware/cookies.rb:613:in `call'
2017-08-14T18:45:04.230983+00:00 app[web.1]: [fc17a4be-c098-4b88-b635-3f52a6e4bb23] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.3/lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
2017-08-14T18:45:04.230984+00:00 app[web.1]: [fc17a4be-c098-4b88-b635-3f52a6e4bb23] vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.3/lib/active_support/callbacks.rb:97:in `run_callbacks'
2017-08-14T18:45:04.230985+00:00 app[web.1]: [fc17a4be-c098-4b88-b635-3f52a6e4bb23] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.3/lib/action_dispatch/middleware/callbacks.rb:24:in `call'
2017-08-14T18:45:04.230986+00:00 app[web.1]: [fc17a4be-c098-4b88-b635-3f52a6e4bb23] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.3/lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
2017-08-14T18:45:04.230986+00:00 app[web.1]: [fc17a4be-c098-4b88-b635-3f52a6e4bb23] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.3/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
2017-08-14T18:45:04.230987+00:00 app[web.1]: [fc17a4be-c098-4b88-b635-3f52a6e4bb23] vendor/bundle/ruby/2.3.0/gems/railties-5.1.3/lib/rails/rack/logger.rb:36:in `call_app'
2017-08-14T18:45:04.230988+00:00 app[web.1]: [fc17a4be-c098-4b88-b635-3f52a6e4bb23] vendor/bundle/ruby/2.3.0/gems/railties-5.1.3/lib/rails/rack/logger.rb:24:in `block in call'
2017-08-14T18:45:04.230989+00:00 app[web.1]: [fc17a4be-c098-4b88-b635-3f52a6e4bb23] vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.3/lib/active_support/tagged_logging.rb:69:in `block in tagged'
2017-08-14T18:45:04.230989+00:00 app[web.1]: [fc17a4be-c098-4b88-b635-3f52a6e4bb23] vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.3/lib/active_support/tagged_logging.rb:26:in `tagged'
2017-08-14T18:45:04.230990+00:00 app[web.1]: [fc17a4be-c098-4b88-b635-3f52a6e4bb23] vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.3/lib/active_support/tagged_logging.rb:69:in `tagged'
2017-08-14T18:45:04.230991+00:00 app[web.1]: [fc17a4be-c098-4b88-b635-3f52a6e4bb23] vendor/bundle/ruby/2.3.0/gems/railties-5.1.3/lib/rails/rack/logger.rb:24:in `call'
2017-08-14T18:45:04.230991+00:00 app[web.1]: [fc17a4be-c098-4b88-b635-3f52a6e4bb23] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.3/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
2017-08-14T18:45:04.230992+00:00 app[web.1]: [fc17a4be-c098-4b88-b635-3f52a6e4bb23] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.3/lib/action_dispatch/middleware/request_id.rb:25:in `call'
2017-08-14T18:45:04.230993+00:00 app[web.1]: [fc17a4be-c098-4b88-b635-3f52a6e4bb23] vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'
2017-08-14T18:45:04.230993+00:00 app[web.1]: [fc17a4be-c098-4b88-b635-3f52a6e4bb23] vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/runtime.rb:22:in `call'
2017-08-14T18:45:04.230995+00:00 app[web.1]: [fc17a4be-c098-4b88-b635-3f52a6e4bb23] vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.3/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
2017-08-14T18:45:04.230998+00:00 app[web.1]: [fc17a4be-c098-4b88-b635-3f52a6e4bb23] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.3/lib/action_dispatch/middleware/executor.rb:12:in `call'
2017-08-14T18:45:04.230999+00:00 app[web.1]: [fc17a4be-c098-4b88-b635-3f52a6e4bb23] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.3/lib/action_dispatch/middleware/static.rb:125:in `call'
2017-08-14T18:45:04.231000+00:00 app[web.1]: [fc17a4be-c098-4b88-b635-3f52a6e4bb23] vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/sendfile.rb:111:in `call'
2017-08-14T18:45:04.231001+00:00 app[web.1]: [fc17a4be-c098-4b88-b635-3f52a6e4bb23] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.3/lib/action_dispatch/middleware/ssl.rb:66:in `call'
2017-08-14T18:45:04.231002+00:00 app[web.1]: [fc17a4be-c098-4b88-b635-3f52a6e4bb23] vendor/bundle/ruby/2.3.0/gems/railties-5.1.3/lib/rails/engine.rb:522:in `call'
2017-08-14T18:45:04.231003+00:00 app[web.1]: [fc17a4be-c098-4b88-b635-3f52a6e4bb23] vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/lib/puma/configuration.rb:224:in `call'
2017-08-14T18:45:04.231003+00:00 app[web.1]: [fc17a4be-c098-4b88-b635-3f52a6e4bb23] vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/lib/puma/server.rb:602:in `handle_request'
2017-08-14T18:45:04.231004+00:00 app[web.1]: [fc17a4be-c098-4b88-b635-3f52a6e4bb23] vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/lib/puma/server.rb:435:in `process_client'
2017-08-14T18:45:04.231005+00:00 app[web.1]: [fc17a4be-c098-4b88-b635-3f52a6e4bb23] vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/lib/puma/server.rb:299:in `block in run'
2017-08-14T18:45:04.231006+00:00 app[web.1]: [fc17a4be-c098-4b88-b635-3f52a6e4bb23] vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

**Comment by kevinhughes27** [comment]
this file needs to be removed: https://github.com/neycodes/shopify_test_app/blob/master/config/initializers/shopify_session_repository.rb

**Comment by kevinhughes27** [comment]
I think your issue is here: https://github.com/neycodes/shopify_test_app/blob/66d35d7158cce90feefd581c7d6cfbf80ce7be36/config/initializers/omniauth.rb#L6 what is that value? I would also recommend callback_path not callback url. In general I wouldn't even set this unless you need to

**Comment by neycodes** [comment]
I had to set callback_url to get it to work at all, this was before using version 7.2.8, as I kept getting the redirection_uri not defined error. I'll remove that line as well as the Shopify_session_repository.rb initializer.

**Comment by neycodes** [comment]
I just tried to install it again from heroku, Still the same error. I deleted the shopify_session_repository.rb file and commented out the callback_url line in omniauth.rb

Here is the heroku log:
```
2017-08-14T19:24:31.405930+00:00 heroku[router]: at=info method=GET path="/" host=shopifyauthtest.herokuapp.com request_id=7a9ead48-3d1d-4aea-9864-86bf84b1f58d fwd="96.232.156.16" dyno=web.1 connect=1ms service=9ms status=302 bytes=1222 protocol=https
2017-08-14T19:24:31.671495+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=shopifyauthtest.herokuapp.com request_id=fef6bee5-4db5-4360-9d8f-f99af4debb59 fwd="96.232.156.16" dyno=web.1 connect=1ms service=2ms status=304 bytes=112 protocol=https
2017-08-14T19:24:42.746334+00:00 heroku[router]: at=info method=GET path="/login?shop=llp-dev.myshopify.com" host=shopifyauthtest.herokuapp.com request_id=0b4fff21-9e5d-45f7-b176-306eab94ee85 fwd="96.232.156.16" dyno=web.1 connect=1ms service=8ms status=304 bytes=1057 protocol=https
2017-08-14T19:24:42.739586+00:00 app[web.1]: [0b4fff21-9e5d-45f7-b176-306eab94ee85] Started GET "/login?shop=llp-dev.myshopify.com" for 96.232.156.16 at 2017-08-14 19:24:42 +0000
2017-08-14T19:24:42.741338+00:00 app[web.1]: [0b4fff21-9e5d-45f7-b176-306eab94ee85] Processing by ShopifyApp::SessionsController#new as HTML
2017-08-14T19:24:42.741562+00:00 app[web.1]: [0b4fff21-9e5d-45f7-b176-306eab94ee85]   Parameters: {"shop"=>"llp-dev.myshopify.com"}
2017-08-14T19:24:42.743011+00:00 app[web.1]: [0b4fff21-9e5d-45f7-b176-306eab94ee85]   Rendering inline template
2017-08-14T19:24:42.743738+00:00 app[web.1]: [0b4fff21-9e5d-45f7-b176-306eab94ee85]   Rendered inline template (0.6ms)
2017-08-14T19:24:42.744017+00:00 app[web.1]: [0b4fff21-9e5d-45f7-b176-306eab94ee85] Completed 200 OK in 2ms (Views: 1.2ms)
2017-08-14T19:24:42.845126+00:00 app[web.1]: [6f6fc2ae-ca2f-4de6-8a2f-c5ee8b114888] Started GET "/auth/shopify?shop=llp-dev.myshopify.com" for 96.232.156.16 at 2017-08-14 19:24:42 +0000
2017-08-14T19:24:42.846065+00:00 app[web.1]: I, [2017-08-14T19:24:42.845972 #17]  INFO -- omniauth: (shopify) Setup endpoint detected, running now.
2017-08-14T19:24:42.846327+00:00 app[web.1]: I, [2017-08-14T19:24:42.846251 #17]  INFO -- omniauth: (shopify) Request phase initiated.
2017-08-14T19:24:42.853089+00:00 heroku[router]: at=info method=GET path="/auth/shopify?shop=llp-dev.myshopify.com" host=shopifyauthtest.herokuapp.com request_id=6f6fc2ae-ca2f-4de6-8a2f-c5ee8b114888 fwd="96.232.156.16" dyno=web.1 connect=0ms service=9ms status=302 bytes=1598 protocol=https
2017-08-14T19:24:52.842131+00:00 app[web.1]: [2dc40edc-8026-4895-bc01-c05e32b2a72c] Started GET "/auth/shopify/callback?code=0dacfad1a363eb18ce90c253f705d243&hmac=5c948790c981d54d0de4d308713a23bec9528f65c2019910200c7fa3c8c62098&shop=llp-dev.myshopify.com&state=e8c0968adabffdecfb3062c6530c1abac80efbf0dd09b7f6&timestamp=1502738692" for 96.232.156.16 at 2017-08-14 19:24:52 +0000
2017-08-14T19:24:52.842875+00:00 app[web.1]: I, [2017-08-14T19:24:52.842793 #17]  INFO -- omniauth: (shopify) Setup endpoint detected, running now.
2017-08-14T19:24:52.843242+00:00 app[web.1]: I, [2017-08-14T19:24:52.843196 #17]  INFO -- omniauth: (shopify) Callback phase initiated.
2017-08-14T19:24:52.844950+00:00 app[web.1]: [2dc40edc-8026-4895-bc01-c05e32b2a72c]   
2017-08-14T19:24:52.844998+00:00 app[web.1]: [2dc40edc-8026-4895-bc01-c05e32b2a72c] TypeError (no implicit conversion of nil into String):
2017-08-14T19:24:52.845037+00:00 app[web.1]: [2dc40edc-8026-4895-bc01-c05e32b2a72c]   
2017-08-14T19:24:52.845116+00:00 app[web.1]: [2dc40edc-8026-4895-bc01-c05e32b2a72c] vendor/bundle/ruby/2.3.0/gems/omniauth-shopify-oauth2-1.2.0/lib/omniauth/strategies/shopify.rb:85:in `hexdigest'
2017-08-14T19:24:52.845118+00:00 app[web.1]: [2dc40edc-8026-4895-bc01-c05e32b2a72c] vendor/bundle/ruby/2.3.0/gems/omniauth-shopify-oauth2-1.2.0/lib/omniauth/strategies/shopify.rb:85:in `hmac_sign'
2017-08-14T19:24:52.845119+00:00 app[web.1]: [2dc40edc-8026-4895-bc01-c05e32b2a72c] vendor/bundle/ruby/2.3.0/gems/omniauth-shopify-oauth2-1.2.0/lib/omniauth/strategies/shopify.rb:60:in `valid_signature?'
2017-08-14T19:24:52.845120+00:00 app[web.1]: [2dc40edc-8026-4895-bc01-c05e32b2a72c] vendor/bundle/ruby/2.3.0/gems/omniauth-shopify-oauth2-1.2.0/lib/omniauth/strategies/shopify.rb:111:in `callback_phase'
2017-08-14T19:24:52.845121+00:00 app[web.1]: [2dc40edc-8026-4895-bc01-c05e32b2a72c] vendor/bundle/ruby/2.3.0/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:230:in `callback_call'
2017-08-14T19:24:52.845122+00:00 app[web.1]: [2dc40edc-8026-4895-bc01-c05e32b2a72c] vendor/bundle/ruby/2.3.0/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:187:in `call!'
2017-08-14T19:24:52.845122+00:00 app[web.1]: [2dc40edc-8026-4895-bc01-c05e32b2a72c] vendor/bundle/ruby/2.3.0/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:167:in `call'
2017-08-14T19:24:52.845123+00:00 app[web.1]: [2dc40edc-8026-4895-bc01-c05e32b2a72c] vendor/bundle/ruby/2.3.0/gems/omniauth-1.6.1/lib/omniauth/builder.rb:63:in `call'
2017-08-14T19:24:52.845124+00:00 app[web.1]: [2dc40edc-8026-4895-bc01-c05e32b2a72c] vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/etag.rb:25:in `call'
2017-08-14T19:24:52.845125+00:00 app[web.1]: [2dc40edc-8026-4895-bc01-c05e32b2a72c] vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/conditional_get.rb:25:in `call'
2017-08-14T19:24:52.845126+00:00 app[web.1]: [2dc40edc-8026-4895-bc01-c05e32b2a72c] vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/head.rb:12:in `call'
2017-08-14T19:24:52.845126+00:00 app[web.1]: [2dc40edc-8026-4895-bc01-c05e32b2a72c] vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:232:in `context'
2017-08-14T19:24:52.845127+00:00 app[web.1]: [2dc40edc-8026-4895-bc01-c05e32b2a72c] vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:226:in `call'
2017-08-14T19:24:52.845128+00:00 app[web.1]: [2dc40edc-8026-4895-bc01-c05e32b2a72c] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.3/lib/action_dispatch/middleware/cookies.rb:613:in `call'
2017-08-14T19:24:52.845131+00:00 app[web.1]: [2dc40edc-8026-4895-bc01-c05e32b2a72c] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.3/lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
2017-08-14T19:24:52.845132+00:00 app[web.1]: [2dc40edc-8026-4895-bc01-c05e32b2a72c] vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.3/lib/active_support/callbacks.rb:97:in `run_callbacks'
2017-08-14T19:24:52.845133+00:00 app[web.1]: [2dc40edc-8026-4895-bc01-c05e32b2a72c] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.3/lib/action_dispatch/middleware/callbacks.rb:24:in `call'
2017-08-14T19:24:52.845134+00:00 app[web.1]: [2dc40edc-8026-4895-bc01-c05e32b2a72c] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.3/lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
2017-08-14T19:24:52.845134+00:00 app[web.1]: [2dc40edc-8026-4895-bc01-c05e32b2a72c] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.3/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
2017-08-14T19:24:52.845135+00:00 app[web.1]: [2dc40edc-8026-4895-bc01-c05e32b2a72c] vendor/bundle/ruby/2.3.0/gems/railties-5.1.3/lib/rails/rack/logger.rb:36:in `call_app'
2017-08-14T19:24:52.845136+00:00 app[web.1]: [2dc40edc-8026-4895-bc01-c05e32b2a72c] vendor/bundle/ruby/2.3.0/gems/railties-5.1.3/lib/rails/rack/logger.rb:24:in `block in call'
2017-08-14T19:24:52.845137+00:00 app[web.1]: [2dc40edc-8026-4895-bc01-c05e32b2a72c] vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.3/lib/active_support/tagged_logging.rb:69:in `block in tagged'
2017-08-14T19:24:52.845137+00:00 app[web.1]: [2dc40edc-8026-4895-bc01-c05e32b2a72c] vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.3/lib/active_support/tagged_logging.rb:26:in `tagged'
2017-08-14T19:24:52.845138+00:00 app[web.1]: [2dc40edc-8026-4895-bc01-c05e32b2a72c] vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.3/lib/active_support/tagged_logging.rb:69:in `tagged'
2017-08-14T19:24:52.845139+00:00 app[web.1]: [2dc40edc-8026-4895-bc01-c05e32b2a72c] vendor/bundle/ruby/2.3.0/gems/railties-5.1.3/lib/rails/rack/logger.rb:24:in `call'
2017-08-14T19:24:52.845140+00:00 app[web.1]: [2dc40edc-8026-4895-bc01-c05e32b2a72c] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.3/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
2017-08-14T19:24:52.845141+00:00 app[web.1]: [2dc40edc-8026-4895-bc01-c05e32b2a72c] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.3/lib/action_dispatch/middleware/request_id.rb:25:in `call'
2017-08-14T19:24:52.845141+00:00 app[web.1]: [2dc40edc-8026-4895-bc01-c05e32b2a72c] vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'
2017-08-14T19:24:52.845142+00:00 app[web.1]: [2dc40edc-8026-4895-bc01-c05e32b2a72c] vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/runtime.rb:22:in `call'
2017-08-14T19:24:52.845144+00:00 app[web.1]: [2dc40edc-8026-4895-bc01-c05e32b2a72c] vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.3/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
2017-08-14T19:24:52.845147+00:00 app[web.1]: [2dc40edc-8026-4895-bc01-c05e32b2a72c] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.3/lib/action_dispatch/middleware/executor.rb:12:in `call'
2017-08-14T19:24:52.845148+00:00 app[web.1]: [2dc40edc-8026-4895-bc01-c05e32b2a72c] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.3/lib/action_dispatch/middleware/static.rb:125:in `call'
2017-08-14T19:24:52.845149+00:00 app[web.1]: [2dc40edc-8026-4895-bc01-c05e32b2a72c] vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/sendfile.rb:111:in `call'
2017-08-14T19:24:52.845150+00:00 app[web.1]: [2dc40edc-8026-4895-bc01-c05e32b2a72c] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.3/lib/action_dispatch/middleware/ssl.rb:66:in `call'
2017-08-14T19:24:52.845151+00:00 app[web.1]: [2dc40edc-8026-4895-bc01-c05e32b2a72c] vendor/bundle/ruby/2.3.0/gems/railties-5.1.3/lib/rails/engine.rb:522:in `call'
2017-08-14T19:24:52.845151+00:00 app[web.1]: [2dc40edc-8026-4895-bc01-c05e32b2a72c] vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/lib/puma/configuration.rb:224:in `call'
2017-08-14T19:24:52.845152+00:00 app[web.1]: [2dc40edc-8026-4895-bc01-c05e32b2a72c] vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/lib/puma/server.rb:602:in `handle_request'
2017-08-14T19:24:52.845153+00:00 app[web.1]: [2dc40edc-8026-4895-bc01-c05e32b2a72c] vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/lib/puma/server.rb:435:in `process_client'
2017-08-14T19:24:52.845153+00:00 app[web.1]: [2dc40edc-8026-4895-bc01-c05e32b2a72c] vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/lib/puma/server.rb:299:in `block in run'
2017-08-14T19:24:52.845154+00:00 app[web.1]: [2dc40edc-8026-4895-bc01-c05e32b2a72c] vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
2017-08-14T19:24:52.846797+00:00 heroku[router]: at=info method=GET path="/auth/shopify/callback?code=0dacfad1a363eb18ce90c253f705d243&hmac=5c948790c981d54d0de4d308713a23bec9528f65c2019910200c7fa3c8c62098&shop=llp-dev.myshopify.com&state=e8c0968adabffdecfb3062c6530c1abac80efbf0dd09b7f6&timestamp=1502738692" host=shopifyauthtest.herokuapp.com request_id=2dc40edc-8026-4895-bc01-c05e32b2a72c fwd="96.232.156.16" dyno=web.1 connect=1ms service=7ms status=500 bytes=1891 protocol=https
```

**Comment by kevinhughes27** [comment]
this can also be removed https://github.com/neycodes/shopify_test_app/blob/743b183fe1ee344cebab6055a90e8e0398f42fb2/config/application.rb#L21-L22 not the issue though.

It looks like it can't find the hmac but it is there in the request. Is it possible some other gem or middleware is removing the param on production? It might be the force ssl

**Comment by neycodes** [comment]
I removed the force_ssl. Same issue. Maybe it's something to do with middleware, I really have no idea at this point.

```
2017-08-14T19:56:51.227684+00:00 app[web.1]: [4e09c590-3ec1-430a-b042-12edcd2e42f3] Started GET "/auth/shopify?shop=livelovetest.myshopify.com" for 96.232.156.16 at 2017-08-14 19:56:51 +0000
2017-08-14T19:56:51.239806+00:00 app[web.1]: I, [2017-08-14T19:56:51.228246 #7]  INFO -- omniauth: (shopify) Setup endpoint detected, running now.
2017-08-14T19:56:51.240452+00:00 app[web.1]: I, [2017-08-14T19:56:51.240364 #7]  INFO -- omniauth: (shopify) Request phase initiated.
2017-08-14T19:56:51.165786+00:00 heroku[router]: at=info method=GET path="/login?shop=livelovetest.myshopify.com" host=shopifyauthtest.herokuapp.com request_id=9dcd9f7a-fcbf-42e6-98f2-46098e980339 fwd="96.232.156.16" dyno=web.1 connect=1ms service=21ms status=200 bytes=2140 protocol=https
2017-08-14T19:56:51.259846+00:00 heroku[router]: at=info method=GET path="/auth/shopify?shop=livelovetest.myshopify.com" host=shopifyauthtest.herokuapp.com request_id=4e09c590-3ec1-430a-b042-12edcd2e42f3 fwd="96.232.156.16" dyno=web.1 connect=1ms service=33ms status=302 bytes=1536 protocol=https
2017-08-14T19:57:27.292766+00:00 heroku[router]: at=info method=GET path="/auth/shopify/callback?code=ee839be3bd0a9680291cc418b101c2d8&hmac=1f924bba5bc06c391941e087610c35a48f34c5ee84753066b2b76c50cb437d8d&shop=livelovetest.myshopify.com&state=46bcb0df8b1cd2df357c358d22a2fa3e1c7179c9cc3f121b&timestamp=1502740647" host=shopifyauthtest.herokuapp.com request_id=d9307361-534d-4be6-a0b5-096c2800dc84 fwd="96.232.156.16" dyno=web.1 connect=0ms service=6ms status=500 bytes=1827 protocol=https
2017-08-14T19:57:27.287171+00:00 app[web.1]: [d9307361-534d-4be6-a0b5-096c2800dc84] Started GET "/auth/shopify/callback?code=ee839be3bd0a9680291cc418b101c2d8&hmac=1f924bba5bc06c391941e087610c35a48f34c5ee84753066b2b76c50cb437d8d&shop=livelovetest.myshopify.com&state=46bcb0df8b1cd2df357c358d22a2fa3e1c7179c9cc3f121b&timestamp=1502740647" for 96.232.156.16 at 2017-08-14 19:57:27 +0000
2017-08-14T19:57:27.287806+00:00 app[web.1]: I, [2017-08-14T19:57:27.287722 #7]  INFO -- omniauth: (shopify) Setup endpoint detected, running now.
2017-08-14T19:57:27.288082+00:00 app[web.1]: I, [2017-08-14T19:57:27.288017 #7]  INFO -- omniauth: (shopify) Callback phase initiated.
2017-08-14T19:57:27.290019+00:00 app[web.1]: [d9307361-534d-4be6-a0b5-096c2800dc84]   
2017-08-14T19:57:27.290144+00:00 app[web.1]: [d9307361-534d-4be6-a0b5-096c2800dc84] TypeError (no implicit conversion of nil into String):
2017-08-14T19:57:27.290183+00:00 app[web.1]: [d9307361-534d-4be6-a0b5-096c2800dc84]   
2017-08-14T19:57:27.290286+00:00 app[web.1]: [d9307361-534d-4be6-a0b5-096c2800dc84] vendor/bundle/ruby/2.3.0/gems/omniauth-shopify-oauth2-1.2.0/lib/omniauth/strategies/shopify.rb:85:in `hexdigest'
2017-08-14T19:57:27.290288+00:00 app[web.1]: [d9307361-534d-4be6-a0b5-096c2800dc84] vendor/bundle/ruby/2.3.0/gems/omniauth-shopify-oauth2-1.2.0/lib/omniauth/strategies/shopify.rb:85:in `hmac_sign'
2017-08-14T19:57:27.290290+00:00 app[web.1]: [d9307361-534d-4be6-a0b5-096c2800dc84] vendor/bundle/ruby/2.3.0/gems/omniauth-shopify-oauth2-1.2.0/lib/omniauth/strategies/shopify.rb:60:in `valid_signature?'
2017-08-14T19:57:27.290291+00:00 app[web.1]: [d9307361-534d-4be6-a0b5-096c2800dc84] vendor/bundle/ruby/2.3.0/gems/omniauth-shopify-oauth2-1.2.0/lib/omniauth/strategies/shopify.rb:111:in `callback_phase'
2017-08-14T19:57:27.290292+00:00 app[web.1]: [d9307361-534d-4be6-a0b5-096c2800dc84] vendor/bundle/ruby/2.3.0/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:230:in `callback_call'
2017-08-14T19:57:27.290294+00:00 app[web.1]: [d9307361-534d-4be6-a0b5-096c2800dc84] vendor/bundle/ruby/2.3.0/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:187:in `call!'
2017-08-14T19:57:27.290295+00:00 app[web.1]: [d9307361-534d-4be6-a0b5-096c2800dc84] vendor/bundle/ruby/2.3.0/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:167:in `call'
2017-08-14T19:57:27.290295+00:00 app[web.1]: [d9307361-534d-4be6-a0b5-096c2800dc84] vendor/bundle/ruby/2.3.0/gems/omniauth-1.6.1/lib/omniauth/builder.rb:63:in `call'
2017-08-14T19:57:27.290296+00:00 app[web.1]: [d9307361-534d-4be6-a0b5-096c2800dc84] vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/etag.rb:25:in `call'
2017-08-14T19:57:27.290297+00:00 app[web.1]: [d9307361-534d-4be6-a0b5-096c2800dc84] vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/conditional_get.rb:25:in `call'
2017-08-14T19:57:27.290297+00:00 app[web.1]: [d9307361-534d-4be6-a0b5-096c2800dc84] vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/head.rb:12:in `call'
2017-08-14T19:57:27.290298+00:00 app[web.1]: [d9307361-534d-4be6-a0b5-096c2800dc84] vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:232:in `context'
2017-08-14T19:57:27.290299+00:00 app[web.1]: [d9307361-534d-4be6-a0b5-096c2800dc84] vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:226:in `call'
2017-08-14T19:57:27.290300+00:00 app[web.1]: [d9307361-534d-4be6-a0b5-096c2800dc84] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.3/lib/action_dispatch/middleware/cookies.rb:613:in `call'
2017-08-14T19:57:27.290301+00:00 app[web.1]: [d9307361-534d-4be6-a0b5-096c2800dc84] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.3/lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
2017-08-14T19:57:27.290301+00:00 app[web.1]: [d9307361-534d-4be6-a0b5-096c2800dc84] vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.3/lib/active_support/callbacks.rb:97:in `run_callbacks'
2017-08-14T19:57:27.290302+00:00 app[web.1]: [d9307361-534d-4be6-a0b5-096c2800dc84] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.3/lib/action_dispatch/middleware/callbacks.rb:24:in `call'
2017-08-14T19:57:27.290303+00:00 app[web.1]: [d9307361-534d-4be6-a0b5-096c2800dc84] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.3/lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
2017-08-14T19:57:27.290303+00:00 app[web.1]: [d9307361-534d-4be6-a0b5-096c2800dc84] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.3/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
2017-08-14T19:57:27.290304+00:00 app[web.1]: [d9307361-534d-4be6-a0b5-096c2800dc84] vendor/bundle/ruby/2.3.0/gems/railties-5.1.3/lib/rails/rack/logger.rb:36:in `call_app'
2017-08-14T19:57:27.290305+00:00 app[web.1]: [d9307361-534d-4be6-a0b5-096c2800dc84] vendor/bundle/ruby/2.3.0/gems/railties-5.1.3/lib/rails/rack/logger.rb:24:in `block in call'
2017-08-14T19:57:27.290306+00:00 app[web.1]: [d9307361-534d-4be6-a0b5-096c2800dc84] vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.3/lib/active_support/tagged_logging.rb:69:in `block in tagged'
2017-08-14T19:57:27.290306+00:00 app[web.1]: [d9307361-534d-4be6-a0b5-096c2800dc84] vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.3/lib/active_support/tagged_logging.rb:26:in `tagged'
2017-08-14T19:57:27.290307+00:00 app[web.1]: [d9307361-534d-4be6-a0b5-096c2800dc84] vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.3/lib/active_support/tagged_logging.rb:69:in `tagged'
2017-08-14T19:57:27.290307+00:00 app[web.1]: [d9307361-534d-4be6-a0b5-096c2800dc84] vendor/bundle/ruby/2.3.0/gems/railties-5.1.3/lib/rails/rack/logger.rb:24:in `call'
2017-08-14T19:57:27.290308+00:00 app[web.1]: [d9307361-534d-4be6-a0b5-096c2800dc84] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.3/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
2017-08-14T19:57:27.290308+00:00 app[web.1]: [d9307361-534d-4be6-a0b5-096c2800dc84] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.3/lib/action_dispatch/middleware/request_id.rb:25:in `call'
2017-08-14T19:57:27.290309+00:00 app[web.1]: [d9307361-534d-4be6-a0b5-096c2800dc84] vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'
2017-08-14T19:57:27.290309+00:00 app[web.1]: [d9307361-534d-4be6-a0b5-096c2800dc84] vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/runtime.rb:22:in `call'
2017-08-14T19:57:27.290311+00:00 app[web.1]: [d9307361-534d-4be6-a0b5-096c2800dc84] vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.3/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
2017-08-14T19:57:27.290314+00:00 app[web.1]: [d9307361-534d-4be6-a0b5-096c2800dc84] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.3/lib/action_dispatch/middleware/executor.rb:12:in `call'
2017-08-14T19:57:27.290315+00:00 app[web.1]: [d9307361-534d-4be6-a0b5-096c2800dc84] vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.3/lib/action_dispatch/middleware/static.rb:125:in `call'
2017-08-14T19:57:27.290315+00:00 app[web.1]: [d9307361-534d-4be6-a0b5-096c2800dc84] vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/sendfile.rb:111:in `call'
2017-08-14T19:57:27.290316+00:00 app[web.1]: [d9307361-534d-4be6-a0b5-096c2800dc84] vendor/bundle/ruby/2.3.0/gems/railties-5.1.3/lib/rails/engine.rb:522:in `call'
2017-08-14T19:57:27.290316+00:00 app[web.1]: [d9307361-534d-4be6-a0b5-096c2800dc84] vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/lib/puma/configuration.rb:224:in `call'
2017-08-14T19:57:27.290317+00:00 app[web.1]: [d9307361-534d-4be6-a0b5-096c2800dc84] vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/lib/puma/server.rb:602:in `handle_request'
2017-08-14T19:57:27.290317+00:00 app[web.1]: [d9307361-534d-4be6-a0b5-096c2800dc84] vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/lib/puma/server.rb:435:in `process_client'
2017-08-14T19:57:27.290317+00:00 app[web.1]: [d9307361-534d-4be6-a0b5-096c2800dc84] vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/lib/puma/server.rb:299:in `block in run'
2017-08-14T19:57:27.290318+00:00 app[web.1]: [d9307361-534d-4be6-a0b5-096c2800dc84] vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

**Comment by kevinhughes27** [comment]
yeah I can't see anything either unfortunately.

**Comment by neycodes** [comment]
I'll create a new skeleton app and try to use an older version of the gem and see if I can get that to work.

**Comment by neycodes** [comment]
shopify_app v7.2.8 works, so I'll have to re-do my actual app to work with that version and rails 4.2.8.

**Comment by neycodes** [comment]
I found the problem. It was a label in my heroku config var, which I missed when I was changing the app over from a private to public app. It installs fine now on v7.4.0.

**Comment by kevinhughes27** [comment]
Glad you found it. It should also work on version 8.0.0 if you are inclined.
