### ISSUE TITLE
Safari ITP cookie screen UX problems

### ISSUE THREAD

**Issue by nwtn** [Shopify/shopify_app#734]
* [ ] the current screen asking for authentication is not responsive on mobile
* [x] ~the auth screen/ITP flow shouldn’t happen at all in shopify mobile, only browsers~ apps should be able to solve this by upgrading to shopify_app 9.0.2
* [ ] the copy is sometimes not showing up in English (need reproduction steps cc @darrinhenein)
* [ ] the copy explicitly mentions third-party apps, even for Shopify-built apps

**Comment by nwtn** [comment]
cc @adamwillking for the copy

**Comment by amythibodeau** [comment]
@adamwillking Just a note that this is a high priority fix. Our POS channel is getting a lot of attention right now and this experience is pretty jank.

**Comment by darrinhenein** [comment]
I was able to reproduce the German language UI just by opening the channel in Shopify Mobile on my Canadian-localized iPhone X, nothing more specific.

Also want to confirm that there is no workaround to this screen? Can we provide a custom version for POS or specific first-party apps?

**Comment by ragalie** [comment]
I wonder if the user agent has changed for Shopify Mobile in a way that `shopify_app` isn't supporting (or maybe `shopify_app` isn't on the latest version of `browser_sniffer`?). I'm pretty sure we set this up so that this screen never appears in Shopify Mobile since ITP doesn't apply in the `WebView`s it's using. cc @francinen

**Comment by darrinhenein** [comment]
![IMG_1B059530D71E-1](https://user-images.githubusercontent.com/792313/57105834-e1a73900-6cf9-11e9-919d-9640e5be3dd6.jpeg)

iOS 12.2

**Comment by ragalie** [comment]
Ok I'm pretty sure a bump to browser_sniffer will significantly decrease the incidence of this since it'll stop this showing up in Shopify Mobile: https://github.com/Shopify/browser_sniffer/commit/7de9740c2a6516315bd456b3d42e21e350410f4d

I'll do that right now and open a PR.

We'll should also add a caution tape bot that reminds people to update `browser_sniffer` in both core *and* shopify_app when they update it.

**Comment by ragalie** [comment]
OK, I opened that PR. After we force the version upgrade here, each app that uses `shopify_app` needs to upgrade the version of `shopify_app` they're using.

@nwtn I'll get reviews on this PR, can you own cutting a new `shopify_app` release after the PR goes in?

**Comment by francinen** [comment]
Thanks, @ragalie!

As for the responsive behaviour, can we double-check if the breakpoints we initially included are being applied (E.g., https://github.com/Shopify/shopify_app/pull/647/commits/47f921af74fab6fe5a1d85701df81f23188fcb52#diff-76cd9c528badf5d6f9be38534035819eR19)?

**Comment by francinen** [comment]
And to clarify what we mean by "third-party apps", the existing content does not use the Shopify definition of "third-party apps"; ITP is concerned about domains accessing cookies in a third-party context. The updated content should distinguish Shopify's definition of third-party apps from ITP's functionality of blocking access to cookies in a third-party context.

**Comment by andrewlo** [comment]
Question: this ITP page affects apps running inside an iFrame in Safari right?

Would this project https://vault.shopify.io/projects/8129 to run apps directly in the Shopify Mobile app instead of in an iframe remove the need for this screen inside the Shopify Mobile app? (it would still show up on a mobile browser though)

**Comment by andrewlo** [comment]
Another problem with this page is that, in Shopify Mobile app, if you go to "Store" -> "Point of Sale", it shows a menu linking to "Setup" and "Overview", the two pages in POS Channel.

However, when you click "Overview", you get the ITP screen show above. But when you click "Continue" it actually brings you to the Setup page (at the root URL "/") instead of the Overview page. Shouldn't this page know which URL the user was trying to access, and redirect back to that URL after?

cc @rahilvirani

**Comment by ragalie** [comment]
The ITP page shouldn't be showing in Shopify Mobile. The PR we're working returns us to expected behaviour of not showing that flow. So I don't think this will be an issue in the mobile app anymore.

If this behaviour is also true in other contexts it's something to look into further but may have an app-specific fix.

**Comment by andrewlo** [comment]
OK great, thanks!

**Comment by nwtn** [comment]
the update to shopify_app with the updated browser_sniffer is now live: https://rubygems.org/gems/shopify_app/versions/9.0.2

apps and channels using shopify_app should upgrade to this version to prevent the ITP screen from showing in shopify mobile. (this likely won’t solve the other issues.)

**Comment by andrewlo** [comment]
![Image from iOS](https://user-images.githubusercontent.com/1470768/57111796-85e5ab80-6d0b-11e9-894f-1287a2701532.png)

^ Just got that in mobile Safari on iOS (my language is set to English). I'm guessing that screen is also from Shopify App gem?

**Comment by nwtn** [comment]
Can someone share 🎩 instructions to get the ITP screen?

**Comment by ragalie** [comment]
For me it happens pretty consistently when loading the admin in a browser on iOS and then opening up an app using `shopify_app`.

**Comment by nwtn** [comment]
Looks like the main problem causing the responsiveness issue is that we’re missing a `<meta name="viewport" content="width=device-width, initial-scale=1">` in the `head` of the ITP files. I can do a PR to fix that and see how far it get us.

**Comment by nwtn** [comment]
#737 should fix responsiveness

**Comment by ashchristopher** [comment]
@ragalie What do we do about 3rd party applications that are using `shopify_app` gem?

**Comment by ragalie** [comment]
They'll need to upgrade to a recent `shopify_app` version. We published some information about this a while ago and sent out an email: https://help.shopify.com/en/api/guides/itp-impact

I don't know if we've done more outreach recently, @nwtn would have better information on that.

**Comment by adamwillking** [comment]
Just a quick update on my end: 

- Today I'll produce some copy as a more  immediate clarification fix
- Next week I'll do a deeper dive into this flow and see how we can improve the content/flow more holistically. 

BRB

**Comment by nwtn** [comment]
> I don't know if we've done more outreach recently

We have not. Once these issues are resolved we can look into the best way to communicate this to partners. We may have to also do point releases on shopify_app 8.x for partners who aren’t ready to adopt API versioning.

**Comment by andrewlo** [comment]
@ragalie @nwtn On web (desktop Safari), I still see that if I try to go to the Overview page in POS Channel from the Admin side nav, after the ITP screens to enable cookies, it always goes back to the Setup page (root page in POS Channel).

Is it possible for ITP page to remember where the user was trying to get to (through URL param like the login pages) and then go straight to that page, rather than always going to the root URL of the app?

Otherwise, it will be even more difficult for a user to go to a specific page within the app or channel.

Thanks!

**Comment by nwtn** [comment]
@andrewlo i saw a PR go through…somewhere…to handle that behaviour. Is that resolved?

Where are we at for the other problems described here?

**Comment by andrewlo** [comment]
@nwtn this PR seems to fix that issue https://github.com/Shopify/shopify_app/pull/664

**Comment by joshreeves** [comment]
@andrewlo @nwtn - Updated #664

**Comment by sergey-alekseev** [comment]
>the copy is sometimes not showing up in English  

Might be related to https://github.com/Shopify/shopify_app/issues/635.

**Comment by emilybulger** [comment]
FYI, recently received the "surprising display of this page in a language other than my system settings" that @darrinhenein originally mentioned here in May. (in my case, Desktop, Firefox)

<img width="384" alt="Screen Shot 2019-12-13 at 3 03 16 PM" src="https://user-images.githubusercontent.com/56970554/71933881-c635dd00-3168-11ea-88ba-3c7e02bad748.png">

**Comment by JimmyMcKegger** [comment]
Hey all,

I saw that you need replication steps for the non-English display issue.

I just got English on my laptop, but was able to replicate the wrong language when adding the Buy Button sales channel on test stores using an iPhone XR (software version 14.6). 

My phone has English and French in the general settings/ browser settings, my requests' locale in the [logs](https://logs.shopify.io/en-GB/app/search/search?sid=1626694121.62213_17CA8B5B-3AC0-415C-8011-3B2B231076A5) shows up as `en-IE` but when I tried to onboard I got the following results:


- Safari browser showed me German:

<img width="305" alt="2021-41-qqx52 b6ohx" src="https://user-images.githubusercontent.com/57632668/126310417-5a11cc10-76e6-462a-bdde-735f143c2816.png">


- Chrome gave me Spanish:

<img width="353" alt="2021-42-ptry5 leuie" src="https://user-images.githubusercontent.com/57632668/126310386-a08bace7-2e4e-490e-a695-a9d121020147.png">


> I also commented on issue 765: `https://github.com/Shopify/shopify_app/issues/765#issuecomment-883173186`
